apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ $.Values.namespace | default "ops360" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.secman_secret_entries }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{  $.Values.secman_name  }}
      property: {{ . }}
  {{- end }}
  {{- if .Values.keystoreEnabled }}
  - secretKey: KEYSTORE_FILE
    remoteRef:
      key: {{  .Values.secman_name  }}
      property: KEYSTORE_FILE
      decodingStrategy: "Base64"
  {{- end }}