apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default "ops360-sa"}}
  namespace: {{ .Values.namespace | default "ops360" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn | default "missing arn" }}