replicaCount: 1
image: 039556708828.dkr.ecr.us-east-1.amazonaws.com/alveo-bpm-admin-ui:1.0.5
servicePorts:
  - name: http
    port: 8080

serviceHealthPath: /healthz

# Routing
ingressName: bpm-admin-ingress
ingressOrder: 30

routePrefix: /bpm-admin
routeHost: "example.com"
routePortName: http

# Probes
# default value 'http'
serviceLivenessProbeName: http
serviceReadinessProbeName: http

# Resources
serviceCpu: 1
serviceMemory: 1Gi

# Service Image Config Path
serviceConfigPath: "/etc/nginx"
