replicaCount: 1
image: 039556708828.dkr.ecr.us-east-1.amazonaws.com/spreadsheet-processing-service:1.0.2
servicePorts:
  - name: http
    port: 9000

serviceHealthPath: /spreadsheets

ingressName: spreadsheet-processing-service-ingress
ingressOrder: 80

# Routing
routePrefix: /spreadsheets
routeHost: "example.com"
routePortName: http

# Probes
# default value 'http'
serviceLivenessProbeName: http
serviceReadinessProbeName: http

# Resources
serviceCpu: 1
serviceMemory: 1G

# Service Image Config Path
serviceConfigPath: "/home/user/app/conf"

## Database Configuration
# Postgres
postgresDb: sps

## Security
serviceAccountName: "spreadsheet-processing-service-sa"

## Security
# Configure Java Keystore
keystoreEnabled: true

# AC Authentication
authEnabled: true

## Secrets
# Auth Service Secrets
secretName: spreadsheet-processing-service-secrets
secretEntries:
  - POSTGRES_USERNAME
  - POSTGRES_PASSWORD
  - POSTGRES_DATABASE
  - POSTGRES_HOST
  - POSTGRES_PORT
  - PLAY_HTTP_SECRET_KEY
  - KEYSTORE_KEY_ALIAS
  - KEYSTORE_KEY_PASSWORD
  - KEYSTORE_PASSWORD
  - KEYSTORE_SIG_ALG
